tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/dupes"

brew "python"
brew "awscli"
brew "bash"
brew "coreutils"
brew "findutils"
brew "git"
brew "git-flow"
brew "grep"
brew "node"
brew "pipenv"
brew "pyenv"
brew "zsh"

cask "insomnia"
cask "slack"
cask "keepassxc"
cask "iterm2"
